
export const hotelsData = [
  {
    id: 1,
    image: 'https://images.trvl-media.com/lodging/1000000/590000/581300/581215/680fb04d.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
    type: 'Complexe',
    name: 'The Residence Tunis',
    location: 'Gammarth, Tunisie',
    stars: 5,
    rating: 9.0,
    ratingText: 'Fabuleux',
    reviews: 1071,
    isGenius: true,
  },
  {
    id: 2,
    image: 'https://admin.tunisiepromo.tn/file_manager/source/La%20Badira/42192660.webp', 
    type: 'Hôtel-boutique',
    name: 'La Badira',
    location: 'Hammamet, Tunisie',
    stars: 5,
    rating: 9.4,
    ratingText: 'Exceptionnel',
    reviews: 854,
    isGenius: true,
  },
  {
    id: 3,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9yA-Q7gD8ROaGOlvgK9IHISMA1WIVMmeolg&s', 
    type: 'Resort & Spa',
    name: 'Anantara Sahara Tozeur',
    location: 'Tozeur, Tunisie',
    stars: 5,
    rating: 9.1,
    ratingText: 'Fabuleux',
    reviews: 512,
    isGenius: false,
  },
  {
    id: 4,
    image: 'https://www.resabo.com/cr.fwk/images/hotels/Hotel-6575-20211006-054423.jpg', 
    type: 'Hôtel de charme',
    name: 'Dar El Jeld Hotel & Spa',
    location: 'Medina de Tunis, Tunisie',
    stars: 5,
    rating: 9.6,
    ratingText: 'Exceptionnel',
    reviews: 430,
    isGenius: true,
  },
  {
    id: 5,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrYOePlzu5Y28tvFomyTn_b7EVoHEpg5Zo9g&s', 
    type: 'Resort',
    name: 'Mövenpick Resort & Marine Spa',
    location: 'Sousse, Tunisie',
    stars: 5,
    rating: 8.5,
    ratingText: 'Très bien',
    reviews: 2150,
    isGenius: false,
  },
  {
    id: 6,
    image: 'https://www.resabo.com/cr.fwk/images/hotels/Hotel-1709-20240716-013703.jpg', 
    type: 'Hôtel & Thalasso',
    name: 'Hasdrubal Prestige Thalassa & Spa',
    location: 'Djerba, Tunisie',
    stars: 5,
    rating: 8.9,
    ratingText: 'Superbe',
    reviews: 998,
    isGenius: true,
  },
  {
    id: 7,
    image: 'https://pix10.agoda.net/hotelImages/5547513/-1/0225c52b3455dffdfb2d5f6fcee112a2.jpg?ca=7&ce=1&s=414x232', 
    type: 'Hôtel',
    name: 'Four Seasons Hotel Tunis',
    location: 'Gammarth, Tunisie',
    stars: 5,
    rating: 9.2,
    ratingText: 'Fabuleux',
    reviews: 780,
    isGenius: false,
  },
  {
    id: 8,
    image: 'https://www.dar-hi.net/imagens/decouvrir/11.jpg', 
    type: 'Eco-lodge & Spa',
    name: 'Dar Hi',
    location: 'Nefta, Tunisie',
    stars: 4,
    rating: 8.8,
    ratingText: 'Superbe',
    reviews: 320,
    isGenius: false,
  },
  {
    id: 9,
    image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/b3/50/ab/lti-les-orangers-garden.jpg?w=900&h=500&s=1', 
    type: 'Villa & Bungalows',
    name: 'The Orangers Garden',
    location: 'Hammamet, Tunisie',
    stars: 5,
    rating: 9.3,
    ratingText: 'Exceptionnel',
    reviews: 1100,
    isGenius: true,
  },
  {
    id: 10,
    image: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/299588069.jpg?k=d0e992ebe2212a5d3c0bd83d687953e85faddc84e808dadcfb1afd78767307e1&o=&hp=1',
    type: 'Club',
    name: 'TUI BLUE Palm Beach Palace',
    location: 'Djerba, Tunisie',
    stars: 5,
    rating: 8.6,
    ratingText: 'Très bien',
    reviews: 1345,
    isGenius: false,
  },
];